docker-build:
  image: docker:latest
  variables:
    DOCKER_DRIVER: overlay
  stage: build & test
  services:
    - docker:dind
  before_script:
  - docker info
  - apk update
  - apk upgrade
  - apk add curl jq python3 python3-dev build-base libffi-dev libressl-dev gettext
  - curl -O https://bootstrap.pypa.io/get-pip.py
  - python3 get-pip.py
  - pip install docker-compose
  script:
    - docker-compose build
    - docker-compose up --exit-code-from cypress
  except:
    - master
